### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by onsails** [astro/socksify-ruby#1]
How is it possible to use socks servers which require authorization?

**Comment by acegilz** [comment]
How do I send the authentication params when making the request? Can you give a request example?

I'm doing like this:

```
proxy: 'socks://x4462826:af87qC4a4n@proxy-nl.privateinternetaccess.com:1080'
```

but always receiving

```
SOCKSError::NotAllowed: connection not allowed by ruleset
```
