### ISSUE TITLE
little code explaination please

### ISSUE THREAD

**Issue by webattitude** [astro/socksify-ruby#23]
Hello, why isn't this https://github.com/astro/socksify-ruby/blob/master/lib/socksify.rb#L178 an infinite loop ?

**Comment by astro** [comment]
Why should it be?

**Comment by webattitude** [comment]
because _initialize_ calls itself through its alias _initialize_tcp_, doesn't it ?

**Comment by webattitude** [comment]
sorry if this is trivial, I'm pretty new to ruby and rails...

**Comment by webattitude** [comment]
It's ok, sorry.
initialize_tcp is an alias for standard TCPSocket#initialize, right ?

**Comment by webattitude** [comment]
I came to know what alias is ^^
sorry to bother
