### ISSUE TITLE
Tests not passing in master

### ISSUE THREAD

**Issue by joeldrapper** [astro/socksify-ruby#35]
The documentation says to send patches via Email, but I can’t see any mention of how to correctly run the tests. If I simply run the test file in master `ruby test/tc_socksify.rb`, I get 7 errors.

**Comment by MatzFan** [comment]
Fixed in #43

@astro if you are happy to have me push future versions to rubygems I think you need to add me as an [owner](https://guides.rubygems.org/command-reference/#gem-owner).
