### ISSUE TITLE
Ruby 2.4/2.5 TCPSocket interface change

### ISSUE THREAD

**Issue by karis10** [astro/socksify-ruby#37]
Socksify library won't be working with many libraries starting from 2.5 ruby version due to standard library interface changes, [FTP](https://github.com/astro/socksify-ruby/issues/34), IMAP, POP3 and possible SMTP TCPSocket internal interface would be changed in favor of raw sockets.

Read about it here: https://bugs.ruby-lang.org/issues/15318

**Comment by MatzFan** [comment]
Net::HTTP library similarly affected as of Ruby 3.1. Gem v1.7.2 fixes Net::HTTP for Ruby > 3.0 but there are no plans to fix other protocols for now so closing.
